defaults: &defaults
  legal_entity: 'the University of Edinburgh, University of Glasgow and the University of California'

  # Warning: The abbreviation here should match the org.abbreviation value registered in your database!
  organisation:
    name: 'EurofleetsPlus'
    abbreviation: 'EF+'  # This value is used to identify the default guidance that get auto-selected when a new plan is created
    url: 'https://github.com/DMPRoadmap/roadmap/wiki'
    copywrite_name: 'Curation Centre (CC)'
    email: 'tvandenberghe@naturalsciences.be'
    helpdesk_email: 'tvandenberghe@naturalsciences.be'
    welcome_links:
      - link1:
        title: 'Data management in Horizon 2020'
        url: 'http://ec.europa.eu/research/participants/docs/h2020-funding-guide/cross-cutting-issues/open-access-data-management/data-management_en.htm'
      - link2:
        title: 'Guidelines on FAIR Data Management in Horizon 2020'
        url: 'http://ec.europa.eu/research/participants/data/ref/h2020/grants_manual/hi/oa_pilot/h2020-hi-oa-data-mgt_en.pdf'

    # Warning: this value will be used to override the URl of the application's built-in contact form. It will
    #          replace the link in all email communications as well as the contact link in the page footer!
    #
    #          Comment this line out if you want to use DMPRoadmap's built-in contact form.
    #contact_us_url: 'https://somewhere.com/contact-us'

  application:
    name: 'DMP Roadmap for EurofleetsPlus'
    url: 'https://github.com/DMPRoadmap/roadmap'
    version: '0.1.0'
    release_notes_url: 'https://github.com/DMPRoadmap/roadmap/wiki/Releases'
    issue_list_url: 'https://github.com/DMPRoadmap/roadmap/issues'
    user_group_subscription_url: 'http://listserv.ucop.edu/cgi-bin/wa.exe?SUBED1=ROADMAP-L&A=1'
    api_documentation_url: 'https://github.com/DMPRoadmap/roadmap/wiki/API-Documentation'

  preferences:
    email:
      users:
        new_comment: true
        admin_privileges: true
        added_as_coowner: true
        feedback_requested: true
        feedback_provided: true
      owners_and_coowners:
        visibility_changed: true

  service_configuration:
    plans:
      org_admins_read_all: true
      super_admins_read_all: true


development:
  <<: *defaults

test:
  <<: *defaults

stage:
  <<: *defaults

production:
  <<: *defaults
